"""Versioned REST surface (/api/v2) generated from the MCP tool contract.

Each v2 operation is POST /api/v2/<tool> and its request body is the MCP
tool's own input schema, so MCP and REST cannot drift: the handler only
authenticates the caller and dispatches through the same MCP call path
(policy, approvals, telemetry, idempotency_key, error contract). A completed
call returns the tool's result with HTTP 200, even when the tool reports
ok=false; a failure returns {"error": <error contract>, "detail": ...} with the
contract's HTTP status.

The published schema openapi/mac-mcp-v2.json is generated by
`python -m mcp_server.rest_v2 --write` and checked for drift by the tests.
API version (API_VERSION) and product version are separate. The original
unversioned routes are unchanged.

Run from the source tree:  python -m mcp_server.rest_v2 [--write]
"""
from __future__ import annotations

import copy
import json
import sys
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Optional

from fastapi import Depends, Request
from fastapi.responses import JSONResponse

API_VERSION = "2.0.0"
SCHEMA_PATH = Path(__file__).resolve().parents[1] / "openapi" / "mac-mcp-v2.json"

# The stable v1 REST selection plus the recommended browser route (#48),
# which v1 never exposed. Every name must be a registered MCP tool.
V2_TOOLS = (
    "run_command", "process_list", "kill_process", "get_system_info",
    "start_background_job", "get_job_status", "get_job_output", "stop_job", "list_jobs", "wait_jobs",
    "run_commands_parallel",
    "write_file", "write_files_batch", "read_file", "read_multiple_files", "edit_file", "move_file", "copy_file",
    "delete_path", "list_directory", "directory_tree", "create_directory", "get_file_info", "find_files",
    "run_applescript", "send_notification", "clipboard_get", "clipboard_set", "open_app", "open_url",
    "set_volume", "get_volume", "set_brightness", "screenshot", "set_reminder", "get_running_apps",
    "artifact_pipeline", "context_handoff", "mac_snapshot", "mac_observe", "mac_act",
    "search_files", "spotlight_search", "http_request",
    "browser_list_tabs", "browser_observe", "browser_find", "browser_act", "browser_do",
    "browser_open_url", "browser_activate_tab", "browser_close_tab", "browser_wait_for_download",
    "browser_upload_artifact", "browser_screenshot", "browser_get_snapshot",
    "ask_user", "ask_choice", "ask_confirmation",
    "memory_search", "memory_get", "skill_list", "skill_search", "skill_get",
)

_DESCRIPTION_PROPERTY = {
    "type": "string", "minLength": 3, "maxLength": 80,
    "description": "Optional short label shown in Mac MCP's activity view (required when that setting is on).",
}

_ERROR_SCHEMA = {
    "type": "object",
    "required": ["error"],
    "properties": {
        "detail": {"description": "Human-readable detail (not the machine contract)."},
        "error": {
            "type": "object",
            "required": ["code", "stage", "outcome", "retry"],
            "properties": {
                "code": {"type": "string"},
                "stage": {"type": "string", "enum": ["validation", "policy", "preflight", "execution"]},
                "outcome": {"type": "string", "enum": ["not_executed", "completed", "unknown"]},
                "retry": {"type": "string", "enum": ["fix_arguments", "safe_retry", "observe_again",
                                                     "wait_for_user", "never_retry"]},
                "http_status": {"type": "integer"},
                "message": {"type": "string"},
                "tool": {"type": "string"},
            },
        },
    },
}


def _hoist_defs(schema: Dict[str, Any], components: Dict[str, Any]) -> Dict[str, Any]:
    """Move a tool schema's local $defs into OpenAPI components and repoint its $refs."""
    schema = copy.deepcopy(schema)
    defs = schema.pop("$defs", None) or {}
    components.update(defs)
    text = json.dumps(schema).replace('"#/$defs/', '"#/components/schemas/')
    # Defaults such as path=Path.home() would publish this machine's home directory.
    home = json.dumps(str(Path.home()))[1:-1]
    text = text.replace(f'"{home}/', '"~/').replace(f'"{home}"', '"~"')
    return json.loads(text)


def request_schema(tool: Any, components: Dict[str, Any]) -> Dict[str, Any]:
    schema = _hoist_defs(dict(getattr(tool, "inputSchema", None) or {}), components)
    schema.pop("title", None)
    properties = dict(schema.get("properties") or {})
    properties.setdefault("description", dict(_DESCRIPTION_PROPERTY))
    schema["properties"] = properties
    schema["required"] = [name for name in schema.get("required") or [] if name != "description"]
    if not schema["required"]:
        schema.pop("required")
    schema["type"] = "object"
    return schema


def build_openapi(tools: Iterable[Any], *, product_version: str) -> Dict[str, Any]:
    by_name = {tool.name: tool for tool in tools}
    missing = [name for name in V2_TOOLS if name not in by_name]
    if missing:
        raise ValueError(f"v2 tools are not registered MCP tools: {', '.join(missing)}")
    components: Dict[str, Any] = {"ErrorContract": _ERROR_SCHEMA}
    paths: Dict[str, Any] = {}
    for name in V2_TOOLS:
        tool = by_name[name]
        paths[f"/api/v2/{name}"] = {"post": {
            "operationId": name,
            "summary": name,
            "description": str(tool.description or "")[:300],
            "requestBody": {"required": True, "content": {"application/json": {
                "schema": request_schema(tool, components)}}},
            "responses": {
                "200": {"$ref": "#/components/responses/Result"},
                "default": {"$ref": "#/components/responses/Error"},
            },
        }}
    return {
        "openapi": "3.1.0",
        "info": {
            "title": "Mac MCP REST API v2",
            "version": API_VERSION,
            "x-product-version": product_version,
            "description": (
                "Versioned REST surface generated from the Mac MCP tool contract: POST /api/v2/<tool> takes the MCP "
                "tool's input schema and runs through the same policy, approvals, telemetry, idempotency_key and "
                "error contract as MCP. Failures return {error: {code, stage, outcome, retry}}. The unversioned "
                "/api routes remain available unchanged."
            ),
        },
        "servers": [{"url": "https://YOUR-MAC-MCP-HOST"}],
        "components": {
            "schemas": components,
            "responses": {
                "Result": {"description": "Completed call; the tool's own result (it may report ok=false).",
                           "content": {"application/json": {"schema": {"type": "object", "additionalProperties": True}}}},
                "Error": {"description": "Failed call (status from the error contract).",
                          "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorContract"}}}},
            },
            "securitySchemes": {"bearerAuth": {"type": "http", "scheme": "bearer"}},
        },
        "security": [{"bearerAuth": []}],
        "paths": paths,
    }


async def contract_tools(mcp: Any) -> List[Any]:
    """MCP tool definitions as published: full descriptions plus idempotency_key on state-changing tools."""
    from mcp.server.fastmcp import FastMCP
    from .observability import ObservedFastMCP

    tools = await FastMCP.list_tools(mcp)
    return [ObservedFastMCP._with_idempotency_schema(tool) for tool in tools]


def install_routes(rest_app: Any, mcp: Any, auth_dependency: Callable[..., Any]) -> None:
    """Add POST /v2/<tool> for every v2 tool (mounted under /api)."""
    from mcp.server.fastmcp.exceptions import ToolError

    from . import error_contract
    from .policy import reset_policy_context, set_policy_context
    from .runtime_settings import tool_activity_setting

    def make_endpoint(tool_name: str):
        async def endpoint(request: Request) -> Any:
            try:
                body = await request.json()
            except ValueError:
                body = None
            if not isinstance(body, dict):
                contract = {"code": "invalid_arguments", "stage": "validation", "outcome": "not_executed",
                            "retry": "fix_arguments", "http_status": 422,
                            "message": "request body must be a JSON object", "tool": tool_name}
                return JSONResponse({"detail": contract["message"], "error": contract}, status_code=422)
            arguments = dict(body)
            if "description" not in arguments and tool_activity_setting("require_descriptions", False):
                arguments["description"] = f"REST v2 {tool_name}"[:80]
            token = set_policy_context(request.state.policy_context)
            try:
                result = await mcp.call_tool(tool_name, arguments)
            except ToolError as exc:
                text = str(exc)
                contract = error_contract.parse(text) or error_contract.describe(exc, tool=tool_name)
                detail = text.split("\n" + error_contract.CONTRACT_PREFIX, 1)[0]
                return JSONResponse({"detail": detail, "error": contract},
                                    status_code=int(contract.get("http_status") or 500))
            finally:
                reset_policy_context(token)
            return JSONResponse(_payload(result))

        endpoint.__name__ = f"v2_{tool_name}"
        return endpoint

    for name in V2_TOOLS:
        rest_app.add_api_route(
            f"/v2/{name}", make_endpoint(name), methods=["POST"], operation_id=f"v2_{name}",
            dependencies=[Depends(auth_dependency)], include_in_schema=False,
        )


def _payload(result: Any) -> Any:
    if isinstance(result, tuple) and len(result) == 2 and isinstance(result[1], dict):
        return result[1].get("result", result[1])
    blocks = result[0] if isinstance(result, tuple) else result
    for block in blocks or []:
        text = getattr(block, "text", None)
        if isinstance(text, str):
            try:
                return json.loads(text)
            except ValueError:
                return {"ok": True, "text": text}
    return {"ok": True}


def _generate() -> Dict[str, Any]:
    import asyncio
    from unittest.mock import patch

    import mcp_server.main as main
    from .observability import ObservedFastMCP
    from .version import __version__

    captured: List[Any] = []

    class Capturing(ObservedFastMCP):
        def __init__(self, *args: Any, **kwargs: Any) -> None:
            super().__init__(*args, **kwargs)
            captured.append(self)

    with patch.object(main, "ObservedFastMCP", Capturing):
        main.create_app()
    return build_openapi(asyncio.run(contract_tools(captured[-1])), product_version=__version__)


def render(document: Dict[str, Any]) -> str:
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def main(argv: Optional[List[str]] = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    text = render(_generate())
    if "--write" in args:
        SCHEMA_PATH.write_text(text, encoding="utf-8")
        print(f"wrote {SCHEMA_PATH}")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
